begin;

create table if not exists public.recommendation_contacts (
  id bigint generated by default as identity primary key,
  recommendation_id bigint not null unique references public.recommendations(id) on delete cascade,
  student_user_id uuid not null references auth.users(id) on delete cascade,
  writer_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.recommendation_contacts enable row level security;

drop policy if exists "Students manage own recommendation contacts" on public.recommendation_contacts;
create policy "Students manage own recommendation contacts"
on public.recommendation_contacts
for all to authenticated
using (student_user_id = auth.uid())
with check (
  student_user_id = auth.uid()
  and exists (
    select 1 from public.recommendations r
    where r.id = recommendation_id
      and r.student_user_id = auth.uid()
  )
);

grant select, insert, update, delete on public.recommendation_contacts to authenticated;
grant usage, select on sequence public.recommendation_contacts_id_seq to authenticated;

insert into public.recommendation_contacts (recommendation_id, student_user_id, writer_email)
select id, student_user_id, author_email
from public.recommendations
where nullif(trim(coalesce(author_email, '')), '') is not null
on conflict (recommendation_id) do update
set writer_email = excluded.writer_email,
    updated_at = now();

-- Writer contact information is private. Public recommendation records retain
-- the writer's name, title, organization, and relationship only.
update public.recommendations
set author_email = null
where author_email is not null;

commit;
